changing permissions of apache-scl-wrapper
I'm trying to edit the scl-wrapper script that starts up apace. I want to run my ruby/node script as part of this one, so that ruby can start up before apache. So far it's been a little unresponsive but I'm hoping this idea will work

diff --git a/scratch b/scratch
--- a/scratch
+++ b/scratch
@@ -79,3 +79,45 @@ WORKDIR /root/scripts
 RUN chmod +x ruby-node.sh
 RUN chmod +x setup.sh
 RUN ./ruby-node.sh
+
+# Install Ruby 2.5 from classic
+
+RUN mkdir /root/packages
+WORKDIR /root/packages
+COPY ruby-2.5.8.tar.gz /root/packages
+RUN tar xzf ruby-2.5.8.tar.gz
+WORKDIR /root/packages/ruby-2.5.8
+RUN ./configure
+RUN make
+RUN make install
+
+# Edit the supervisord file 
+RUN sed '7,13d' /opt/rh/httpd24/root/usr/sbin/httpd-scl-wrapper
+RUN echo 'set ENV BASH_ENV="/root/scripts/ruby-node.sh" \\n\
+        ENV="/root/scripts/ruby-node.sh" \\n\\n\
+        PROMPT_COMMAND=". /root/scripts/ruby-node.sh"\n\
+    scl enable rh-ruby25 rh-nodejs10 bash\n\
+    status=$?\n\
+    if [ $status -ne 0 ]; then\n\
+        echo "Failed to start ruby and node.js: $status"\n\
+        exit $status\n\
+    fi\n\
+    unset BASH_ENV PROMPT_COMMAND ENV\n\
+    . /opt/rh/httpd24/service-environment\n\
+    for sclname in $HTTPD24_HTTPD_SCLS_ENABLED ; do\n\
+        . /opt/rh/$sclname/enable\n\
+        export X_SCLS="$X_SCLS $sclname"\n\
+    done\n\
+\n\
+    exec /opt/rh/httpd24/root/usr/sbin/httpd "$@"\n'\
+
+
+[program:apache]
+command=/opt/rh/httpd24/root/usr/sbin -D FOREGROUND
+priority=999
+
+# Copy in the wrapper script
+RUN mkdir /root/scripts
+COPY ruby-node.sh /root/scripts
+WORKDIR /root/scripts
+RUN chmod +x ruby-node.sh
